osdu:
  delfi:
    filePortal:
      url: https://signed-url-dot-p4d-ddl-eu-services.appspot.com/
    portal:
      appkey: PtVguojl2DUr0qimhDclNMwZAeAJwK1T
      url: https://api.evq.csp.slb.com/
gcp:
  storage:
    tempLocationBucket: osdu-gcp-temp-location
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000