osdu:
  delfi:
    filePortal:
      url: https://signed-url-dot-p4d-ddl-eu-services.appspot.com
    portal:
      appkey: PtVguojl2DUr0qimhDclNMwZAeAJwK1T
      url: https://api.evq.csp.slb.com
gcp:
  storage:
    tempLocationBucket: osdu-gcp-temp-location
spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      FAIL_ON_EMPTY_BEANS: false