image: maven:3-jdk-8

stages:
  - test
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

cache:
  paths:
    - .m2/repository/

verify:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  except:
    - master

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS package
  only:
    - master

deploy:
  stage: deploy
  image: google/cloud-sdk
  script:
    - gcloud builds submit -t gcr.io/$GCP_PROJECT/$CI_PROJECT_NAME
    - gcloud beta run deploy $CI_PROJECT_NAME --image gcr.io/$GCP_PROJECT/$CI_PROJECT_NAME --platform managed --region us-central1
  only: 
    - master
