image: maven:3-jdk-8

stages:
  - test
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "-T2 --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

cache:
  paths:
    - .m2/repository/

verify:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS verify sonar:sonar -Dsonar.host.url=https://sonar.osdu-gcp.dev -Dsonar.projectKey=osdu-gcp -Dsonar.login=$SONAR_TOKEN -Dsonar.coverage.jacoco.xmlReportsPath=target/site/jacoco/jacoco.xml
  artifacts:
    reports:
      junit:
        - service/delivery/target/surefire-reports/TEST-*.xml
        - service/ingest/target/surefire-reports/TEST-*.xml
        - service/search/target/surefire-reports/TEST-*.xml

.deploy_template: &deploy_template
  stage: deploy
  image: google/cloud-sdk
  cache: {}
  script:
    - echo "$GCP_SVC_ACCT" > account.json
    - gcloud auth activate-service-account --key-file account.json
    - gcloud config set project $GCP_PROJECT
    - gcloud builds submit --substitutions=_SERVICE_NAME=$SERVICE,_SHORT_SHA=$CI_COMMIT_SHORT_SHA,_CACHE_BUCKET=$GCS_CACHE_BUCKET
    - gcloud beta run deploy $SERVICE --image gcr.io/$GCP_PROJECT/osdu-gcp-$SERVICE:$CI_COMMIT_SHORT_SHA --platform managed --region us-central1 --allow-unauthenticated --memory 512M

deploy_search:
  <<: *deploy_template
  variables:
    SERVICE: search
  only:
    refs:
      - master
      - develop
    changes:
      - pom.xml
      - service/pom.xml
      - common/**/*
      - service/search/**/*
      - service/delfi-client/**/*
      - service/srn-mapper/**/*
      - Dockerfile
      - cloudbuild.yaml

deploy_delivery:
  <<: *deploy_template
  variables:
    SERVICE: delivery
  only:
    refs:
      - master
      - develop
    changes:
      - pom.xml
      - service/pom.xml
      - common/**/*
      - service/delivery/**/*
      - service/delfi-client/**/*
      - service/srn-mapper/**/*
      - Dockerfile
      - cloudbuild.yaml

deploy_ingest:
  <<: *deploy_template
  variables:
    SERVICE: ingest
  only:
    refs:
      - master
      - develop
    changes:
      - pom.xml
      - service/pom.xml
      - common/**/*
      - service/ingest/**/*
      - service/delfi-client/**/*
      - service/srn-mapper/**/*
      - Dockerfile
      - cloudbuild.yaml
