steps:
  - name: 'gcr.io/$PROJECT_ID/restore_cache'
    args: [
            '--bucket=gs://${_CACHE_BUCKET}',
            '--key=maven-$(find -name pom.xml -exec cksum {} \; | cksum | cut -d " " -f1)',
            '--key_fallback=maven-' ]
  - name: 'maven:3-jdk-8-alpine'
    entrypoint: 'mvn'
    # parallel builds (-T2) hang for some reason
    args: [
            'package', '--batch-mode', '--errors', '--fail-at-end', 
            '--show-version', '-DinstallAtEnd=true', '-DdeployAtEnd=true', '-DskipTests', 
            '-Dmaven.repo.local=/workspace/.m2/repository', 
            '-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN',
            '-Djava.awt.headless=true', '-Dhttps.protocols=TLSv1.2'
          ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '--build-arg', 'SERVICE_NAME=${_SERVICE_NAME}',
            '-t', 'gcr.io/$PROJECT_ID/osdu-gcp-${_SERVICE_NAME}:${_SHORT_SHA}',
            '-t', 'gcr.io/$PROJECT_ID/osdu-gcp-${_SERVICE_NAME}:latest',
            '-f', 'Dockerfile.cloudbuild',
            '.' ]
  - name: 'gcr.io/$PROJECT_ID/save_cache'
    args: [
            '--bucket=gs://${_CACHE_BUCKET}',
            '--key=maven-$(find -name pom.xml -exec cksum {} \; | cksum | cut -d " " -f1)',
            '--path=.m2/repository',
            '--no-clobber' ]
images:
  - 'gcr.io/$PROJECT_ID/osdu-gcp-${_SERVICE_NAME}'
