git:
  folder:
    path: resources/git
search:
  delfi:
    portal:
      url: https://api.evq.csp.slb.com/
    client:
      appKeyHeader: AppKey
      authorizationHeader: Authorization
      partitionHeader: slb-data-partition-id
      serverUrl: https://api.evq.csp.slb.com/
  mapper:
    delfi:
      appkey: ${search.mapper.delfi.applicationKey:PtVguojl2DUr0qimhDclNMwZAeAJwK1T}
    searchEndpoint: de/search/v2/query

