osdu:
  processing:
    thread-pool-capacity: 3
    fields-to-strip: location, kind, signedUrl
  delfi:
    filePortal:
      url: https://signed-url-dot-p4d-ddl-eu-services.appspot.com/
    portal:
      appkey: PtVguojl2DUr0qimhDclNMwZAeAJwK1T
      url: https://api.evq.csp.slb.com/
