steps:
  - name: 'gcr.io/$PROJECT_ID/restore_cache'
    args: [
            '--bucket=gs://${_CACHE_BUCKET}',
            '--key=maven-$(find -name pom.xml -exec cksum {} \; | cksum | cut -d " " -f1)',
            '--key_fallback=maven-'
    ]
  - name: 'maven:3-jdk-8-alpine'
    entrypoint: 'mvn'
    env:
      - 'MAVEN_REPO_USER=$_MAVEN_REPO_USER'
      - 'MAVEN_REPO_PASS=$_MAVEN_REPO_PASS'
    # parallel builds (-T2) hang for some reason
    args: [
            'package', '-s', '.m2/settings.xml', '--batch-mode', '--errors', '--fail-at-end',
            '--show-version', '-DinstallAtEnd=true', '-DdeployAtEnd=true', '-DskipTests',
            '-Dmaven.repo.local=/workspace/.m2/repository',
            '-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN',
            '-Djava.awt.headless=true', '-Dhttps.protocols=TLSv1.2'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '--build-arg', 'PROVIDER_NAME=${_PROVIDER_NAME}',
            '-t', 'gcr.io/$PROJECT_ID/os-ingest/ingest-${_PROVIDER_NAME}:${_SHORT_SHA}',
            '-t', 'gcr.io/$PROJECT_ID/os-ingest/ingest-${_PROVIDER_NAME}:latest',
            '-f', 'Dockerfile.cloudbuild',
            '.'
    ]
  - name: 'gcr.io/$PROJECT_ID/save_cache'
    args: [
            '--bucket=gs://${_CACHE_BUCKET}',
            '--key=maven-$(find -name pom.xml -exec cksum {} \; | cksum | cut -d " " -f1)',
            '--path=.m2/repository',
            '--no-clobber'
    ]
images:
  - 'gcr.io/$PROJECT_ID/os-ingest/ingest-${_PROVIDER_NAME}'
